adc: iio: hardware: add buffering support to the powerboard ADC
linux-automation/tacd pull request #27
Opened 2023-06-13 09:41 UTC by hnez

This PR adds buffering support to the powerboard ADC. The main benefit of this change is that voltage and current samples are now taken at the exact same point int time, enabling better instantaneous power measurements.

This feature relies on kernel support for buffering in the powerboard ADC and a fix to `libiio` to allow enabling the buffer for the ADC, both of which are not currently included in `meta-lxatac`.

Related Pull Requests
----------

- [ ] The `meta-lxatac` PR that coordinates the kernel and libiio update, as well as adding this feature linux-automation/meta-lxatac#47

2023-09-25 12:29 UTC, Emantor approved these changes

2023-09-25 12:59 UTC, KarlK90 requested changes

2023-09-25 12:59 UTC, KarlK90 commented on src/adc/iio/hardware.rs
> +type ChannelDesc = (&'static str, &'static str, &'static str);
I would rather introduce a real struct at this point like, which makes it clearer what each string mean.

```rust
struct AdcChannelDesc {
  name: &'static str,
  xxx: &'static str,
  zzz: &'static str,
}
```

2023-09-25 12:59 UTC, KarlK90 commented on src/adc/iio/hardware.rs
> +const TIMESTAMP_ERROR: u64 = u64::MAX;
As discussed: please annotate why the program will never reach `u64::MAX` during its runtime and it is therefore safe to use this magic value.

2023-09-26 13:41 UTC, hnez commented on src/adc/iio/hardware.rs
> +            panic!("Failed to read from ADC");
I've added a commit that at least pushes the error handling out of `src/adc/iio/hardware.rs` for this and some other cases.

https://github.com/linux-automation/tacd/blob/7b71bd9816648832b60a184e942c3486f74bf96c/src/adc/iio/hardware.rs#L214-L216

The error handling is still not particularly great but it's at least shifted one step out of the core hardware abstractions (and towards the user) now.

2023-09-27 08:32 UTC, Emantor approved these changes

2023-09-27 08:33 UTC, merged