web: allow editing the ssh authorized_keys from the web interface
linux-automation/tacd pull request #5
Opened 2023-02-15 12:03 UTC by hnez

This PR adds the `authorized_keys` file for root to the list of config files that can be edited from the web interface.

![tacd-webui-authorized_keys](https://user-images.githubusercontent.com/1273320/219020722-7cdf943d-4219-4b96-9515-99a9bbe44e80.png)

I've stumbled over the need for something like this while writing the LXA TAC quick start guide, as there needs to be some way to first get access to the TAC.

This has obvious and serious security implications, as anyone who can access the web interface can now gain root on the device.
This is a feature in plain sight and anyone setting up a TAC for the first time will get across it, so at least it is not like some telnet port with default passwords on some other IoT devices.
Instead the clear message is _"everyone on a network with a TAC can do whatever they want with it (design your network accordingly)"_.
At least until we get around to implementing proper authentication.

2023-02-19 11:32 UTC, SmithChart commented
I think I am fine with this feature as long as it is easy to find - so no one using the device can complain about this authentication bypass.
But to be honest: Currently everybody with physical access can login via serial per default credentials anyway.

A simple solution could be to add some sort of killswitch to this feature:
* You are free to change the ``authorized_keys`` as often as you want.
* But once you click that button that feature is disabled permanently. We could implement this by touching a file somewhere, e.g. `/home/root/.ssh/authorized_keys_web_edit_disabled``.
* But since we don't have means to factory-default our devices right now this would mean that a user would have to use the serial port to reset this.

But to be honest: I tend to push this feature into the next device generation and not implement it for the current prototypes.

2023-02-23 10:30 UTC, hnez commented
Alright, I would be okay with merging this.

@jluebbe if you are okay with this as well and willing give your approval feel free to merge it.

2023-02-23 13:11 UTC, SmithChart approved these changes

2023-02-23 13:40 UTC, jluebbe requested changes
Where do we want to show the warning about using it in secure networks only?

Perhaps on the main page with a accept button?

2023-02-23 13:40 UTC, jluebbe commented on web/src/SettingsSSH.tsx
> +              label: "Authorized Keys",
```suggestion
              label: "Authorized Keys for root",
```

2023-02-23 13:41 UTC, jluebbe commented
An alternative implementation would be to require a button press as confirmation when saving the config file.

2023-02-24 11:09 UTC, hnez commented on web/src/SettingsSSH.tsx
> +              label: "Authorized Keys",
`… for root`
sounds good. Have updated the PR.

2023-02-24 11:26 UTC, hnez commented
> Where do we want to show the warning about using it in secure networks only?
> Perhaps on the main page with a accept button?

I would need some place to store the accept button state, we do not have that yet in the daemon (and would prefer not implementing it as a one-off now). Sooo … browser local storage maybe?

I would prefer not to train the users to click away some warning message whenever they open the tacd interface. So I would prefer just having it in the manual and other documentation.

> An alternative implementation would be to require a button press as confirmation when saving the config file.

Sounds good and not too difficult to implement.

I do however fear that implementing that kind of "authentication" now could be a reason for us to push implementing actual authentication further into the future.

2023-02-27 09:11 UTC, SmithChart commented
> > Where do we want to show the warning about using it in secure networks only?
> > Perhaps on the main page with a accept button?
> 
> I would need some place to store the accept button state, we do not have that yet in the daemon (and would prefer not implementing it as a one-off now). Sooo … browser local storage maybe?

I would prefer to store this on the device itself. We could add a file for tacd persistent state and migrate that on update.

> 
> I would prefer not to train the users to click away some warning message whenever they open the tacd interface. So I would prefer just having it in the manual and other documentation.

Same here. That's also why I would vote against browser local storage. Paranoid people tend to wipe such stuff. And than we would present them with this question every time they access the device. Also every developer would have to accept it on every device.

> 
> > An alternative implementation would be to require a button press as confirmation when saving the config file.
> 
> Sounds good and not too difficult to implement.

Wouldn't this make remote configuration extra difficult?
Maybe we are over-engineering this feature in this Phase of the project.

2023-02-27 16:25 UTC, jluebbe commented
> > > Where do we want to show the warning about using it in secure networks only?
> > > Perhaps on the main page with a accept button?
> > 
> > 
> > I would need some place to store the accept button state, we do not have that yet in the daemon (and would prefer not implementing it as a one-off now). Sooo … browser local storage maybe?
> 
> I would prefer to store this on the device itself. We could add a file for tacd persistent state and migrate that on update.

That would mean that the warning is only visible for one user, as we have no way to track which user has already seen this message. Browser local storage seems a natural fit.

> > I would prefer not to train the users to click away some warning message whenever they open the tacd interface. So I would prefer just having it in the manual and other documentation.
> 
> Same here. That's also why I would vote against browser local storage. Paranoid people tend to wipe such stuff. And than we would present them with this question every time they access the device. Also every developer would have to accept it on every device.

With storage in the browser, every user needs to confirm it once per device.

> > > An alternative implementation would be to require a button press as confirmation when saving the config file.
> > >
> > Sounds good and not too difficult to implement.
> 
> Wouldn't this make remote configuration extra difficult? Maybe we are over-engineering this feature in this Phase of the project.

Only for adding SSH keys, for which this additional check seems reasonable.

2023-02-27 17:20 UTC, SmithChart commented
> > > > Where do we want to show the warning about using it in secure networks only?
> > > > Perhaps on the main page with a accept button?
> > > 
> > > 
> > > I would need some place to store the accept button state, we do not have that yet in the daemon (and would prefer not implementing it as a one-off now). Sooo … browser local storage maybe?
> > 
> > 
> > I would prefer to store this on the device itself. We could add a file for tacd persistent state and migrate that on update.
> 
> That would mean that the warning is only visible for one user, as we have no way to track which user has already seen this message. Browser local storage seems a natural fit.

That depends on what you want to achieve. If every user should see it at least one: You are right.
So we should get our user story right before discussing the technical details.

> 
> > > I would prefer not to train the users to click away some warning message whenever they open the tacd interface. So I would prefer just having it in the manual and other documentation.
> > 
> > 
> > Same here. That's also why I would vote against browser local storage. Paranoid people tend to wipe such stuff. And than we would present them with this question every time they access the device. Also every developer would have to accept it on every device.
> 
> With storage in the browser, every user needs to confirm it once per device.

Same argument as above.

> 
> > > > An alternative implementation would be to require a button press as confirmation when saving the config file.
> > > 
> > > 
> > > Sounds good and not too difficult to implement.
> > 
> > 
> > Wouldn't this make remote configuration extra difficult? Maybe we are over-engineering this feature in this Phase of the project.
> 
> Only for adding SSH keys, for which this additional check seems reasonable.

A user would still be able to add new keys via ssh itself. So this is probably reasonable.

An alternative could still be to only allow to SSH-keys via web interface once. (See my suggestion above.)
With this we would only have state on the device and would not need to interact with buttons or browser local storage.

As I said: We should make sure we do not over-engineer this solution in this stage of the project.

2023-03-01 13:16 UTC, SmithChart commented
FTR: We had a discussion in real life:
We will implement a `config mode` in the tacd webinterface. In this mode a user can add ssh-keys and set the URL of the labgrid coordinator.
This mode is available at first boot. Afterwards the tacd keeps the state that it already has been configured and does not provide the config mode.
However a user can select the config mode via physical buttons on the device (from the menu).

2023-04-04 14:24 UTC, hnez commented
The requested changes have been implemented in #18, which supersedes this PR.

2023-04-04 14:24 UTC, closed without merging