dut_power: implement an error-free grace period after DUT power on
linux-automation/tacd pull request #58
Opened 2024-02-23 13:21 UTC by hnez

This solves a problem we see with some DUTs and DUT power supplies where the DUT refuses to turn back on due to e.g. a persistent `PolarityInversion` error.

These errors are caused by leakage currents from the DUT power supply interfering with our high impedance voltage measurement. These currents result in actual measurable voltages on the DUT power switch output pins, which are measured by the ADC and interpreted as erroneous.

This PR ignores voltage measurements that would normally result in overvoltage / undervoltage / overcurrent errors _while the power supply is already off_ and also shortly after turning it on (to give the measurements some time to settle).
It should thus not impact our goal of protecting the DUT from actual overvoltages, inverted polarities and overcurrent events, because the turn-on is only a transient event and while the switch is already off there is nothing we could do to protected the device even more.

I would like to split the reviewing process on this PR into two:

  - @SmithChart should review if the intent matches what we want to achieve
  - @KarlK90 should review if the code matches the intent

2024-02-23 13:48 UTC, hnez commented
The failing CI job is unrelated to these changes and should be fixed by #59.
I would prefer merging that one first and rebasing this PR on top of it because I do not want failing CI jobs in the main branch.

2024-02-26 08:24 UTC, SmithChart approved these changes
The logical changes in the diagnosis look good to me.

Additionally I've tested the PR on my device on my desk:
To provoke the InvertedPolarity condition reliably I have connected -9V (that was the wall wart I had lying around) to the output.
With the stock tacd I am not able to switch the Power Switch to on.
With this change the output is turned on momentarily and switched off shortly after.
=> LGTM!

2024-03-12 09:28 UTC, KarlK90 requested changes
The changes itself LGTM, but I would directly work with a `Duration` for the grace period. The number of cycles (previously 6) is tied to the `THREAD_INTERVAL` anyway, so why not make it explicit.

2024-03-12 09:28 UTC, KarlK90 commented on src/dut_power.rs
> +const TURN_ON_ERROR_GRACE_PERIOD: u32 = 6;
```suggestion
const TURN_ON_ERROR_GRACE_PERIOD: Duration = Duration::from_millis(600);
```

2024-03-12 09:28 UTC, KarlK90 commented on src/dut_power.rs
> +                if grace_period == 0 {
```suggestion
                if grace_period == Duration::Zero {
```

2024-03-12 09:28 UTC, KarlK90 commented on src/dut_power.rs
> +                    OutputState::On => grace_period.saturating_sub(1),
```suggestion
                    OutputState::On => grace_period.saturating_sub(THREAD_INTERVAL),
```

2024-03-13 07:58 UTC, KarlK90 approved these changes

2024-03-13 08:06 UTC, merged