http_server: serve license files
linux-automation/tacd pull request #76
Opened 2024-08-05 14:19 UTC by hnez

Some open source license require shipping the license text along with the built software.
To comply with this requirement we let yocto generate a directory with license texts inside of it and expose it via the web interface.

This is what this will look like to the user:

![Licenses Link](https://github.com/user-attachments/assets/1bd7e654-4419-492a-9bfb-f9a1efcc3152)

A new entry "Software Licenses" was added to the web interface (bottom left).

---

![List of packets](https://github.com/user-attachments/assets/ca1d3999-c769-45b2-bf0b-8067033c8810)

Clicking it leads to a directory listing, containing the packages that went into the image file.

---

![License files in packet](https://github.com/user-attachments/assets/244ed4ee-8d0c-4f4b-982b-ce17e0fcf455)

Clicking on one of the package links reveals the license file of said project.
Clicking on one of them shows a plain text file in the browser.

2024-08-05 14:20 UTC, hnez commented
I've assigned this to @jluebbe first to decide if this is what we want.
Deciding if this is implemented in a way we want is a separate task and can be done afterwards.

2024-08-06 14:20 UTC, hnez commented
A stated in linux-automation/meta-lxatac#163 we also want to expose the license manifest file, because it includes software version information.
This will likely not need any modifications here, just a quick check if the file displays correctly and that the `tacd` does not stumble over it being a symlink (if we implement it that way).

2024-08-23 15:03 UTC, hnez commented
> This will likely not need any modifications here, just a quick check if the file displays correctly and that the `tacd` does not stumble over it being a symlink (if we implement it that way).

Not quite how it turned out. Symlinking the manifest file would have required some hacks on the `meta-lxatac` side, so instead decided to "do it properly" and serve the manifest file and the license text files at different locations and use React code to tie them together.
The result can be seen in the screenshots above.
The manifest file is parsed in the web browser and is displayed as a table containing the package name, version and license. The license link is clickable and leads to the license text.

2024-08-23 15:32 UTC, jluebbe approved these changes

2024-08-30 14:09 UTC, hnez commented
Hi @KarlK90, I know that web development is your secret passion.
Could you have a look at this PR from a Rust and Typescript perspective?

2024-09-02 08:04 UTC, KarlK90 commented
> Hi @KarlK90, I know that web development is your secret passion. Could you have a look at this PR from a Rust and Typescript perspective?

I'm sorry to inform you that this is not true, but I'll try my best. :wink:

2024-09-02 13:59 UTC, KarlK90 requested changes
@hnez LGTM, but if possible I would like to see a unit-test for the license file.

2024-09-02 13:59 UTC, KarlK90 commented on web/src/Legal.tsx
> +  // LICENSE: GPL-2.0-or-later
How stable is the format generated by [`poky/meta/classes-recipe/license_image.bbclass`](https://github.com/yoctoproject/poky/blob/master/meta/classes-recipe/license_image.bbclass#L85-L88)? How hard would it be to have some kind of unit-test against a recent license file?

2024-09-02 13:59 UTC, KarlK90 commented on web/src/Legal.tsx
> +            <Link href={"/docs/legal/files/" + p.recipe_name}>{p.license}</Link>
I first thought that we could just set the mime type in the link on the front end, but we also generate a file listing. So you're approach is probably a good abstraction.

2024-09-09 09:02 UTC, hnez commented
> @hnez LGTM, but if possible I would like to see a unit-test for the license file.

Now that I have re-read this message I am not too sure if I actually implemented what you have asked for.
I've just pushed a few commits just now that add a web interface unit test for parsing the included demo_mode manifest file.

But that does not check against a recent _actual_ manifest file. That would be a bit more involved, because the manifest is generated in meta-lxatac, not in the tacd.

We _could_ add a test there, to check if the format did not change. But I think just keeping an eye on the yocto release notes for changes to the file format may be a better option. I would assume that a (breaking) change to the manifest file format would be treated as noteworthy enough to be listed in the release notes.

2024-09-09 10:16 UTC, SmithChart commented
We could also add an integration test into `labgrid-lxatac` to check if the functionality on the actual device does still work. Or is the manifest processed during buildtime?

2024-09-09 15:12 UTC, SmithChart commented
> The manifest is only processed at runtime, so that would be an option. The actual parsing does however take place in the browser and not on the TAC, making a full integration test complicated.

Indeed. I'll add it our test backlog anyway. So if we really want to we can add Selenium or what ever is the browser-test-engine-of-the-day to our dependencies.

2024-09-10 11:52 UTC, hnez commented
Hi, it would be great to get this merged, since it is the only open PR before we can start preparing a new meta-lxatac release.

I am not quite sure if there is anything I need to do.

2024-09-10 14:06 UTC, merged